#!/bin/bash

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

OpenFOAM-6-gcc-central()
{
   # MY
   #set -x

   # Important locations.
   #export inst_loc=/nopt/nrel/ecom/wind/OpenFOAM
   #export spack_loc=/nopt/nrel/ecom/wind
   #export sowfa_loc=/nopt/nrel/ecom/wind/OpenFOAM

   # MY
   export inst_loc=/opt
   export spack_loc=/home/user/proj
   export sowfa_loc=/home/user/proj

   # Load the right modules.
   echo "Purging and loading modules..."
   module purge
   #module use $spack_loc/spack/share/spack/modules/linux-centos7-x86_64/gcc-8.4.0
   module use $spack_loc/spack/share/spack/modules/linux-ubuntu18.04-x86_64_v4/gcc-8.4.0

   #module load gcc/8.4.0
   # will be loaded by hdf5
   #module load openmpi/4.0.4
   #module load openmpi/4.1.5
   module load cgal/4.12
   module load boost/1.69.0
   # unable to buld
   #module load mpfr/4.0.1
   #module load mpfr/4.0.2
   #module load mpfr/4.1.1
   module load mpfr/4.2.0
   module load gmp/6.1.2
   module load scotch/6.0.6
   module load metis/5.1.0
   module load parmetis/4.0.3
   module load flex/2.6.3
   module load hdf5/1.10.6
   module load openblas/0.3.5
   module load yaml-cpp/0.6.2
   #module load zlib/1.2.11
   #module load zlib/1.3
   #module load libxml2/2.9.8
   # too old & incompatible with openfast 3.5.0
   #module load cmake/3.13.3
   module load cmake/3.27.6
   module load zoltan/3.83

   # my crutch
   #module unload gcc-8.4.0/mpich/4.1.2/mh62
   module unload libxml2/2.9.8/cqcz
#   module load gcc-8.4.0/openmpi/4.0.4/fhxg

   module list

   # Unset OpenFOAM environment variables.
   if [ -z "$FOAM_INST_DIR" ]; then
      echo "Nothing to unset..."
   else
      echo "     *Unsetting OpenFOAM environment variables..."
      if [ -f "$FOAM_ETC/config.sh/unset" ]; then
         . $FOAM_ETC/config.sh/unset
      else
         . $FOAM_ETC/config/unset.sh
      fi
   fi

   # Set the OpenFOAM version and installation directory
   export OPENFOAM_VERSION=6
   export OPENFOAM_NAME=OpenFOAM-$OPENFOAM_VERSION
   export FOAM_INST_DIR=$inst_loc
   #export WM_PROJECT_USER_DIR=/home/$USER/$USER-$OPENFOAM_VERSION
   export WM_PROJECT_USER_DIR=/home/$USER/OpenFOAM/$USER-$OPENFOAM_VERSION
   export FOAMY_HEX_MESH=true
   
   # Source the OpenFOAM main environment.
   foamDotFile=$inst_loc/openfoam$OPENFOAM_VERSION/etc/bashrc
   if [ -f $foamDotFile ] ; then
      echo "Sourcing $foamDotFile..."
      source $foamDotFile
   fi

   # For wmake compiling.
   export WM_NCOMPPROCS=16
   export WM_COLOURS="white blue green cyan red magenta yellow"

   # Alias to tutorials.
   alias tut='cd /home/$USER/OpenFOAM/$USER-$OPENFOAM_VERSION/tutorials'
   
   # Set the SOWFA installation directory.
   export SOWFA_DIR=$sowfa_loc/SOWFA-$OPENFOAM_VERSION
   export SOWFA_APPBIN=$SOWFA_DIR/platforms/$WM_OPTIONS/bin
   export SOWFA_LIBBIN=$SOWFA_DIR/platforms/$WM_OPTIONS/lib
   # the code shows that OpenFAST 3.5.0 is supported (although it still depends on deprecated libs!)
   export OPENFAST_DIR=$sowfa_loc/ThirdParty-$OPENFOAM_VERSION/openfast-3.5.0/install
   #export OPENFAST_DIR=$sowfa_loc/ThirdParty-$OPENFOAM_VERSION/openfast-2.6.0/install
   export LD_LIBRARY_PATH=$SOWFA_LIBBIN:$OPENFAST_DIR/lib:$LD_LIBRARY_PATH
   export PATH=$SOWFA_APPBIN:$OPENFAST_DIR/bin:$PATH

   #set +x
}
